# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Live For Code
subtitle: ''
description: ''
keywords:
author: Live For Code
language: zh-cn
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://www.notes.worstone.cn
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing index.html from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tag
archive_dir: archive
category_dir: category
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 5
  order_by: -date

archive_generator:
  path: ''
  per_page: 10
  order_by: -date
  yearly: true  
  monthly: false 

# Category & Tag
default_category: uncategorized
category_map:
tag_map:


meta_generator: false


date_format: YYYY-MM-DD
time_format: HH:mm:ss

Updated_option: false


per_page: 5
pagination_dir: page


include:
exclude:
ignore:


plugins:
  hexo-generator-feed

theme: LiveForCode


deploy:
  type: git
  repo: https://github.com/first19326/first19326.github.io.git
  branch: master

feed:
  type: atom
  path: atom.xml
  limit: 10

algolia:
  applicationID: 010C3EANT8
  apiKey: c7abab9f11b79102b9aff7fe6d41447d
  indexName: Notes
